# Name of your site
name: CohortEx Editor
auth_short_name: Pablo
auth_long_name: Pablo J. Madril

# Short description
description: Cohort Parameters Editor

# Your name, as you want it to appear underneath each post and in the footer
author: Pablo J. Madril

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://pmadril.github.io/CohortExEditor/

# Exclude system files
exclude: [.gitignore]

markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

permalink: /blog/:year/:month/:day/:title

collections:
  stdyPosts:
    output: true
  posts:
    output: true


